# Docker purely for /anubis app

version: "3.9"

services:
#  nginx:
#    image: nginx:1.11.10-alpine
#    ports:
#      - '6969:80'  # or 3000
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  anubis:
    restart: on-failure
    build: .
#    command: tail -F anything  # just for testing
#    image: composer:2.5.4
#    build:
#      context: .
#      target: development
#      args:
#        NODE_ENV: development
#    image: cs-api-strapi:dev
    volumes:
      - /opt/anubis/vendor  # excluded
      - ./Slimfony/.:/opt/Slimfony
      - ./anubis/.:/opt/anubis
    ports:
      - '6969:80'

  db:
    restart: on-failure
    image: postgres:15.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: slimfony
      POSTGRES_USER: root
      POSTGRES_PASSWORD: slimfonyIsSlim
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
