# Docker purely for /slimfonytest app

version: "3.9"

services:
#  nginx:
#    image: nginx:1.11.10-alpine
#    ports:
#      - '6969:80'  # or 3000
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  slimfony-test:
    restart: on-failure
    build: .
#    command: tail -F anything  # just for testing
#    image: composer:2.5.4
#    build:
#      context: .
#      target: development
#      args:
#        NODE_ENV: development
#    image: cs-api-strapi:dev
    volumes:
      - ./Slimfony/.:/opt/Slimfony
      - ./slimfonytest/.:/opt/slimfonytest
      - /opt/slimfonytest/vendor  # excluded
    ports:
      - '6969:80'
